### ISSUE TITLE
Heroku problems

### ISSUE THREAD

**Issue by Dooomsickle** [titaniumnetwork-dev/Ultraviolet-Node-Archive#18] opened 2022-03-23 14:54 UTC
Hi there,

I've noticed that when trying to deploy to Heroku, there is an application error.
If you could fix this it would be greatly appreciated!

**Comment by shirt-dev** [comment] 2022-03-28 20:26
Duplicate of #11 .

No support will be given for Heroku as they are actively blocking this repo.

**Closed as completed by shirt-dev** 2022-03-28 20:26 UTC
Labels: duplicate, wontfix
